import { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { useQueryClient, useQuery } from "@tanstack/react-query";
import { apiRequest, clearCsrfToken } from "./queryClient";
import type { SafetySign } from "@/types";

export type Role = "admin" | "manager" | "editor" | "viewer";
export type Module = "users" | "content" | "sections" | "forms" | "reports" | "settings" | "activity" | "ncr" | "documents";
export type Action = "create" | "read" | "update" | "delete" | "send_email";

export interface User { id:string; name:string; email:string; password:string; role:Role; isActive:boolean; avatar?:string|null; joinedAt:string; }
export interface Section { id:string; name:string; slug:string; description?:string|null; isVisible:boolean; order:number; }
export interface FormField { id:string; type:string; label:string; placeholder?:string; required:boolean; options?:string[]; }
export interface FormTemplate { id:string; title:string; description?:string|null; fields:FormField[]; createdAt:string; status:string; }
export interface Report { id:string; title:string; type:string; generatedBy:string; createdAt:string; status:string; data?:any; }
export interface SafetyReport { id:string; reportNo:string; observationId:string|null; date:string; time:string|null; location:string|null; department:string|null; observerName:string|null; riskLevel:string; category:string|null; status:string; observationDescription:string|null; correctiveAction:string|null; image1:string|null; image2:string|null; image3:string|null; image4:string|null; createdBy:string; createdAt:string; updatedAt:string|null; sourceFile:string|null; sourceMetadata:any; }
export interface ReportSettingsData { id:string; plantPrefix:string; dateFormat:string; resetRule:string; companyName:string; companyLogo:string|null; templateTitle:string; publicBaseUrl:string|null; }
export interface Post { id:string; title:string; content:string; authorId:string; sectionId?:string|null; status:string; createdAt:string; tags:string[]|null; }
export interface ActivityLog { id:string; action:string; details:string; performedBy:string; performedByName:string; timestamp:string; module:Module; }
export type NCRSeverity="low"|"medium"|"high"|"critical";
export type NCRStatus="draft"|"submitted"|"assigned"|"in_progress"|"closed";
export interface NCRActionRow { no:number; action:string; responsible:string; dueDate:string; effectiveness:string; signature:string; }
export interface NCR { id:string; refNo:string; date:string; department:string; location:string|null; description:string; severity:string; immediateAction?:string|null; rootCause?:string|null; correctiveAction?:string|null; correctiveActions?:NCRActionRow[]|null; responsiblePersonId?:string|null; dueDate?:string|null; verificationNotes?:string|null; closedAt?:string|null; image1?:string|null; image2?:string|null; image3?:string|null; image4?:string|null; status:string; createdAt:string; createdBy:string; sourceFile?:string|null; sourceMetadata?:any; }
export interface Department { id:string; name:string; code:string; }
export interface Plant { id:string; refNo:string|null; title:string|null; status:string|null; department:string|null; date:string|null; data:Record<string,any>; createdBy:string|null; createdAt:string; updatedAt:string; }
export interface Employee { id:string; name:string; email:string; title:string; departmentId:string; isPrimary:boolean; }
export interface RoutingRule { id:string; departmentId?:string|null; severity?:string|null; recipientIds:string[]|null; }
export interface DocumentItem { id:string; docType:string; refNo:string; title:string; date:string; vendor:string|null; department:string|null; status:string; category:string|null; description:string|null; amount:string|null; expiryDate:string|null; metadata:any; pdfUrl:string|null; extractedData:any; createdBy:string; createdAt:string; updatedAt:string|null; }
export interface SectionConfigData { id?:string; sectionType:string; categories:string[]|null; requiredFields:string[]|null; numberPrefix:string|null; numberFormat:string; }
export type ColorTheme="ocean"|"emerald"|"violet";
export interface DocumentBranding { companyName:string; companyLogo:string; companyAddress:string; companyPhone:string; companyEmail:string; companyWebsite:string; documentFooter:string; confidentialLabel:string; departmentName:string; safetyDepartmentName:string; logoPosition:'left'|'center'|'right'; heroTitleEn?:string; heroTitleAr?:string; heroSubtitleEn?:string; heroSubtitleAr?:string; heroDescriptionEn?:string; heroDescriptionAr?:string; systemFooterTextEn?:string; systemFooterTextAr?:string; }
export interface SiteSettings { id:string; siteName:string; description:string; allowRegistration:boolean; maintenanceMode:boolean; language:"en"|"ar"; theme:"light"|"dark"; colorTheme?:ColorTheme; branding?:DocumentBranding; }
export interface EmailConfig { id:string; smtpHost:string; smtpPort:string; username:string; password?:string|null; fromName:string; fromEmail:string; enableSending:boolean; signature?:string|null; }
export interface PermissionRow { id:string; role:string; module:string; actions:string[]|null; }

interface DataContextType {
  users:User[]; posts:Post[]; sections:Section[]; forms:FormTemplate[]; reports:Report[]; ncrs:NCR[]; activityLogs:ActivityLog[]; settings:SiteSettings; emailConfig:EmailConfig; departments:Department[]; plants:Plant[]; employees:Employee[]; routingRules:RoutingRule[]; permissionRows:PermissionRow[]; currentUser:User|null; isAuthenticated:boolean; isLoading:boolean;
  login:(email:string,password:string)=>Promise<void>; logout:()=>Promise<void>; hasPermission:(module:Module,action:Action)=>boolean; updatePermission:(role:Role,module:Module,action:Action,granted:boolean)=>void;
  addUser:(u:any)=>Promise<void>; updateUser:(id:string,d:any)=>Promise<void>; deleteUser:(id:string)=>Promise<void>; toggleUserStatus:(id:string)=>Promise<void>; resetUserPassword:(id:string,newPassword?:string)=>Promise<void>;
  addPost:(p:any)=>Promise<void>; updatePost:(id:string,d:any)=>Promise<void>; deletePost:(id:string)=>Promise<void>;
  addSection:(s:any)=>Promise<void>; updateSection:(id:string,d:any)=>Promise<void>; deleteSection:(id:string)=>Promise<void>; reorderSections:(draggedId:string,targetId:string)=>void;
  addForm:(f:any)=>Promise<void>; updateForm:(id:string,d:any)=>Promise<void>; deleteForm:(id:string)=>Promise<void>;
  deleteReport:(id:string)=>Promise<void>; generateReport:(type:string)=>Promise<void>;
  addNCR:(n:any)=>Promise<NCR>; updateNCR:(id:string,d:any)=>Promise<void>; deleteNCR:(id:string)=>Promise<void>; sendNCREmail:(id:string,extraRecipients?:string[])=>Promise<void>;
  updateSettings:(d:Partial<SiteSettings>)=>Promise<void>; updateEmailConfig:(d:Partial<EmailConfig>)=>Promise<void>;
  addDepartment:(d:any)=>Promise<void>; deleteDepartment:(id:string)=>Promise<void>; addPlant:(d:any)=>Promise<Plant>; updatePlant:(id:string,d:any)=>Promise<void>; deletePlant:(id:string)=>Promise<void>; addEmployee:(d:any)=>Promise<void>; updateEmployee:(id:string,d:any)=>Promise<void>; deleteEmployee:(id:string)=>Promise<void>; addRoutingRule:(d:any)=>Promise<void>; deleteRoutingRule:(id:string)=>Promise<void>;
  safetyReports:SafetyReport[]; reportSettingsData:ReportSettingsData; addSafetyReport:(d:any)=>Promise<SafetyReport>; updateSafetyReport:(id:string,d:any)=>Promise<void>; deleteSafetyReport:(id:string)=>Promise<void>; updateReportSettings:(d:Partial<ReportSettingsData>)=>Promise<void>;
  sendTestEmail:(to:string)=>Promise<void>; toggleLanguage:()=>void; toggleTheme:()=>void; setColorTheme:(t:ColorTheme)=>void; exportData:()=>void; importData:(j:string)=>boolean; logActivity:(a:string,d:string,m:Module)=>void;
  documents:DocumentItem[]; sectionConfigs:SectionConfigData[]; addDocument:(d:any)=>Promise<DocumentItem>; updateDocument:(id:string,d:any)=>Promise<void>; deleteDocument:(id:string)=>Promise<void>; updateSectionConfig:(t:string,d:any)=>Promise<void>;
  safetySigns:SafetySign[]; addSafetySign:(d:Partial<SafetySign>)=>Promise<SafetySign>; updateSafetySign:(id:string,d:Partial<SafetySign>)=>Promise<void>; deleteSafetySign:(id:string)=>Promise<void>; recordSignPrint:(id:string)=>void; recordSignView:(id:string)=>void;
}
const DataContext=createContext<DataContextType|undefined>(undefined);
const emptySettings:SiteSettings={id:"main",siteName:"ABDULKAREM SAFETY BOARD",description:"",allowRegistration:true,maintenanceMode:false,language:"en",theme:"dark",colorTheme:"emerald",branding:{companyName:"ABDULKAREM SAFETY BOARD",companyLogo:"/logo.png",companyAddress:"",companyPhone:"",companyEmail:"",companyWebsite:"",documentFooter:"",confidentialLabel:"STRICTLY CONFIDENTIAL",departmentName:"Health & Safety Department",safetyDepartmentName:"Corporate Safety & Environment",logoPosition:"left"}};

export function DataProvider({children}:{children:ReactNode}){
 const queryClient=useQueryClient();
 const [currentUser,setCurrentUser]=useState<User|null>(null); const isAuthenticated=!!currentUser;
 const [localLanguage,setLocalLanguage]=useState<"en"|"ar">(()=>{try{return localStorage.getItem("safety-board-language") === "ar" ? "ar" : "en";}catch{return "en";}});
 const {data:me,isLoading:authLoading}=useQuery<User|null>({queryKey:["/api/auth/me"],queryFn:async()=>{try{const r=await apiRequest("GET","/api/auth/me"); return await r.json();}catch{return null;}},retry:false});
 useEffect(()=>{setCurrentUser(me||null);},[me]);
 const {data:users=[]}=useQuery<User[]>({queryKey:["/api/users"],enabled:isAuthenticated});
 const {data:posts=[]}=useQuery<Post[]>({queryKey:["/api/posts"],enabled:isAuthenticated});
 const {data:sections=[]}=useQuery<Section[]>({queryKey:["/api/sections"],enabled:isAuthenticated});
 const {data:forms=[]}=useQuery<FormTemplate[]>({queryKey:["/api/forms"],enabled:isAuthenticated});
 const {data:reports=[]}=useQuery<Report[]>({queryKey:["/api/reports"],enabled:isAuthenticated});
 const {data:ncrs=[]}=useQuery<NCR[]>({queryKey:["/api/ncr"],enabled:isAuthenticated});
 const {data:activityLogs=[]}=useQuery<ActivityLog[]>({queryKey:["/api/activity-logs"],enabled:isAuthenticated});
 const {data:departments=[]}=useQuery<Department[]>({queryKey:["/api/departments"],enabled:isAuthenticated});
 const {data:plants=[]}=useQuery<Plant[]>({queryKey:["/api/plants"],enabled:isAuthenticated});
 const {data:employees=[]}=useQuery<Employee[]>({queryKey:["/api/employees"],enabled:isAuthenticated});
 const {data:routingRules=[]}=useQuery<RoutingRule[]>({queryKey:["/api/routing-rules"],enabled:isAuthenticated});
 const {data:permissionRows=[]}=useQuery<PermissionRow[]>({queryKey:["/api/permissions"],enabled:isAuthenticated});
 const {data:safetyReports=[]}=useQuery<SafetyReport[]>({queryKey:["/api/safety-reports"],enabled:isAuthenticated});
 const {data:documents=[]}=useQuery<DocumentItem[]>({queryKey:["/api/documents"],enabled:isAuthenticated});
 const {data:sectionConfigs=[]}=useQuery<SectionConfigData[]>({queryKey:["/api/section-config"],enabled:isAuthenticated});
 const {data:emailConfig={id:"main",smtpHost:"",smtpPort:"587",username:"",fromName:"",fromEmail:"",enableSending:false,signature:""}}=useQuery<EmailConfig>({queryKey:["/api/email-settings"],enabled:isAuthenticated});
 const {data:reportSettingsData={id:"main",plantPrefix:"PLT",dateFormat:"YYYY-MM-DD",resetRule:"yearly",companyName:"ABDULKAREM",companyLogo:null,templateTitle:"Safety Report",publicBaseUrl:null}}=useQuery<ReportSettingsData>({queryKey:["/api/report-settings"],enabled:isAuthenticated});
 const safetySignsQueryKey="/api/safety-signs";
 const {data:safetySigns=[]}=useQuery<SafetySign[]>({queryKey:[safetySignsQueryKey],queryFn:async()=>{const r=await apiRequest("GET",`${safetySignsQueryKey}?resource=safety-signs`);const payload=await r.json();if(!r.ok)throw new Error(payload?.error||"Unable to load safety signs");return payload;},enabled:isAuthenticated});
 const {data:remoteSettings=emptySettings}=useQuery<SiteSettings>({queryKey:["/api/site-settings"],queryFn:async()=>{try{const r=await apiRequest("GET","/api/site-settings");return r.ok?await r.json():emptySettings;}catch{return emptySettings;}},enabled:isAuthenticated,staleTime:30000});
 const settings={...emptySettings,...remoteSettings,language:localLanguage};
 const invalidate=(key:string)=>queryClient.invalidateQueries({queryKey:[key]});
 const login=async(email:string,password:string)=>{await apiRequest("POST","/api/auth/login",{email,password}); await queryClient.invalidateQueries({queryKey:["/api/auth/me"]});};
 const logout=async()=>{await fetch("/api/auth/logout",{method:"POST",credentials:"include"}); setCurrentUser(null); clearCsrfToken(); queryClient.clear();};
 const hasPermission=(module:Module,action:Action)=>!!currentUser&&(currentUser.role==="admin"||permissionRows.find(p=>p.role===currentUser.role&&p.module===module)?.actions?.includes(action)===true);
 const updatePermission=async(role:Role,module:Module,action:Action,granted:boolean)=>{const row=permissionRows.find(p=>p.role===role&&p.module===module);let actions=row?.actions?[...row.actions]:[];actions=granted?Array.from(new Set([...actions,action])):actions.filter(a=>a!==action);await apiRequest("PUT","/api/permissions",{role,module,actions});invalidate("/api/permissions");};
 const addUser=async(d:any)=>{await apiRequest("POST","/api/users",d);invalidate("/api/users")}; const updateUser=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/users/${id}`,d);invalidate("/api/users")}; const deleteUser=async(id:string)=>{await apiRequest("DELETE",`/api/users/${id}`);invalidate("/api/users")}; const toggleUserStatus=async(id:string)=>{const u=users.find(x=>x.id===id);if(u) await updateUser(id,{isActive:!u.isActive})}; const resetUserPassword=async(id:string,newPassword?:string)=>{await apiRequest("POST",`/api/users/${id}/change-password`,{newPassword:newPassword||""})};
 const addPost=async(d:any)=>{await apiRequest("POST","/api/posts",d);invalidate("/api/posts")}; const updatePost=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/posts/${id}`,d);invalidate("/api/posts")}; const deletePost=async(id:string)=>{await apiRequest("DELETE",`/api/posts/${id}`);invalidate("/api/posts")};
 const addSection=async(d:any)=>{await apiRequest("POST","/api/sections",d);invalidate("/api/sections")}; const updateSection=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/sections/${id}`,d);invalidate("/api/sections")}; const deleteSection=async(id:string)=>{await apiRequest("DELETE",`/api/sections/${id}`);invalidate("/api/sections")}; const reorderSections=async(draggedId:string,targetId:string)=>{const dragged=sections.find(s=>s.id===draggedId);const target=sections.find(s=>s.id===targetId);if(!dragged||!target||dragged.order===target.order)return;await Promise.all([updateSection(draggedId,{order:target.order}),updateSection(targetId,{order:dragged.order})]);};
 const addForm=async(d:any)=>{await apiRequest("POST","/api/forms",d);invalidate("/api/forms")}; const updateForm=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/forms/${id}`,d);invalidate("/api/forms")}; const deleteForm=async(id:string)=>{await apiRequest("DELETE",`/api/forms/${id}`);invalidate("/api/forms")};
 const deleteReport=async(id:string)=>{await apiRequest("DELETE",`/api/reports/${id}`);invalidate("/api/reports")}; const generateReport=async(type:string)=>{await apiRequest("POST","/api/reports",{title:"Generated Report",type,generatedBy:currentUser?.id||"",status:"completed"});invalidate("/api/reports")};
 const addNCR=async(d:any)=>{const r=await apiRequest("POST","/api/ncr",d);const item=await r.json();invalidate("/api/ncr");return item}; const updateNCR=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/ncr/${id}`,d);invalidate("/api/ncr")}; const deleteNCR=async(id:string)=>{await apiRequest("DELETE",`/api/ncr/${id}`);invalidate("/api/ncr")}; const sendNCREmail=async(id:string,extraRecipients:string[]=[])=>{await apiRequest("POST","/api/ncr/send",{ncrId:id,extraRecipients})};
 const updateSettings=async(d:Partial<SiteSettings>)=>{if(d.language==="ar"||d.language==="en"){setLocalLanguage(d.language);try{localStorage.setItem("safety-board-language",d.language);}catch{}}try{await apiRequest("PATCH","/api/site-settings",d);}catch{}invalidate("/api/site-settings");}; const updateEmailConfig=async(d:Partial<EmailConfig>)=>{await apiRequest("PATCH","/api/email-settings",d);invalidate("/api/email-settings")};
 const addDepartment=async(d:any)=>{await apiRequest("POST","/api/departments",d);invalidate("/api/departments")}; const deleteDepartment=async(id:string)=>{await apiRequest("DELETE",`/api/departments/${id}`);invalidate("/api/departments")}; const addPlant=async(d:any)=>{const r=await apiRequest("POST","/api/plants",d);const item=await r.json();if(!r.ok)throw new Error(item?.error||"Unable to create plant");invalidate("/api/plants");return item}; const updatePlant=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/plants/${id}`,d);invalidate("/api/plants")}; const deletePlant=async(id:string)=>{await apiRequest("DELETE",`/api/plants/${id}`);invalidate("/api/plants")}; const addEmployee=async(d:any)=>{await apiRequest("POST","/api/employees",d);invalidate("/api/employees")}; const updateEmployee=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/employees/${id}`,d);invalidate("/api/employees")}; const deleteEmployee=async(id:string)=>{await apiRequest("DELETE",`/api/employees/${id}`);invalidate("/api/employees")}; const addRoutingRule=async(d:any)=>{await apiRequest("POST","/api/routing-rules",d);invalidate("/api/routing-rules")}; const deleteRoutingRule=async(id:string)=>{await apiRequest("DELETE",`/api/routing-rules/${id}`);invalidate("/api/routing-rules")};
 const addSafetyReport=async(d:any)=>{const r=await apiRequest("POST","/api/safety-reports",d);const item=await r.json();invalidate("/api/safety-reports");return item}; const updateSafetyReport=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/safety-reports/${id}`,d);invalidate("/api/safety-reports")}; const deleteSafetyReport=async(id:string)=>{await apiRequest("DELETE",`/api/safety-reports/${id}`);invalidate("/api/safety-reports")}; const updateReportSettings=async(d:Partial<ReportSettingsData>)=>{await apiRequest("PATCH","/api/report-settings",d);invalidate("/api/report-settings")};
 const sendTestEmail=async(to:string)=>{await apiRequest("POST","/api/email-settings/test",{to})};
 const toggleLanguage=()=>{setLocalLanguage(prev=>{const next=prev==="ar"?"en":"ar";try{localStorage.setItem("safety-board-language",next);}catch{};return next;});};
 const toggleTheme=()=>{void updateSettings({theme:settings.theme==="dark"?"light":"dark"})}; const setColorTheme=(t:ColorTheme)=>{void updateSettings({colorTheme:t});};
 const exportData=()=>{const blob=new Blob([JSON.stringify({ncrs,safetyReports,documents,users,plants},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="safety-board-export.json";a.click();URL.revokeObjectURL(a.href)};
 const importData=(jsonData:string)=>{try{JSON.parse(jsonData);return true}catch{return false}}; const logActivity=(a:string,d:string,m:Module)=>{void apiRequest("POST","/api/activity-logs",{action:a,details:d,module:m}).then(()=>invalidate("/api/activity-logs"))};
 const addDocument=async(d:any)=>{const r=await apiRequest("POST","/api/documents",d);const item=await r.json();invalidate("/api/documents");return item}; const updateDocument=async(id:string,d:any)=>{await apiRequest("PATCH",`/api/documents/${id}`,d);invalidate("/api/documents")}; const deleteDocument=async(id:string)=>{await apiRequest("DELETE",`/api/documents/${id}`);invalidate("/api/documents")}; const updateSectionConfig=async(t:string,d:any)=>{await apiRequest("PUT",`/api/section-config/${encodeURIComponent(t)}`,d);invalidate("/api/section-config")};
 const addSafetySign=async(d:Partial<SafetySign>)=>{const r=await apiRequest("POST",`${safetySignsQueryKey}?resource=safety-signs`,d);const item=await r.json();if(!r.ok)throw new Error(item?.error||"Unable to create safety sign");invalidate(safetySignsQueryKey);return item};
 const updateSafetySign=async(id:string,d:Partial<SafetySign>)=>{const r=await apiRequest("PATCH",`${safetySignsQueryKey}/${encodeURIComponent(id)}?resource=safety-signs&id=${encodeURIComponent(id)}`,d);const item=await r.json();if(!r.ok)throw new Error(item?.error||"Unable to update safety sign");invalidate(safetySignsQueryKey)};
 const deleteSafetySign=async(id:string)=>{const r=await apiRequest("DELETE",`${safetySignsQueryKey}/${encodeURIComponent(id)}?resource=safety-signs&id=${encodeURIComponent(id)}`,undefined);if(!r.ok){const item=await r.json().catch(()=>({}));throw new Error(item?.error||"Unable to delete safety sign");}invalidate(safetySignsQueryKey)};
 const recordSignPrint=async(id:string)=>{try{const r=await apiRequest("POST",`${safetySignsQueryKey}/${encodeURIComponent(id)}/print?resource=safety-signs&id=${encodeURIComponent(id)}&action=print`,undefined);if(r.ok)invalidate(safetySignsQueryKey);}catch{}};
 const recordSignView=async(id:string)=>{try{const r=await apiRequest("POST",`${safetySignsQueryKey}/${encodeURIComponent(id)}/view?resource=safety-signs&id=${encodeURIComponent(id)}&action=view`,undefined);if(r.ok)invalidate(safetySignsQueryKey);}catch{}};
 const value={users,posts,sections,forms,reports,ncrs,activityLogs,settings,emailConfig,departments,plants,employees,routingRules,permissionRows,currentUser,isAuthenticated,isLoading:authLoading,login,logout,hasPermission,updatePermission,addUser,updateUser,deleteUser,toggleUserStatus,resetUserPassword,addPost,updatePost,deletePost,addSection,updateSection,deleteSection,reorderSections,addForm,updateForm,deleteForm,deleteReport,generateReport,addNCR,updateNCR,deleteNCR,sendNCREmail,updateSettings,updateEmailConfig,addDepartment,deleteDepartment,addPlant,updatePlant,deletePlant,addEmployee,updateEmployee,deleteEmployee,addRoutingRule,deleteRoutingRule,safetyReports,reportSettingsData,addSafetyReport,updateSafetyReport,deleteSafetyReport,updateReportSettings,sendTestEmail,toggleLanguage,toggleTheme,setColorTheme,exportData,importData,logActivity,documents,sectionConfigs,addDocument,updateDocument,deleteDocument,updateSectionConfig,safetySigns,addSafetySign,updateSafetySign,deleteSafetySign,recordSignPrint,recordSignView};
 return <DataContext.Provider value={value}>{children}</DataContext.Provider>;
}
export function useData(){const ctx=useContext(DataContext);if(!ctx)throw new Error("useData must be used within DataProvider");return ctx;}
