services:
  mediamtx:
    image: bluenviron/mediamtx:1
    container_name: abdulkarem-camera-gateway
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./data:/data
