export const GENERIC_COLUMNS = new Set(["id", "ref_no", "title", "status", "department", "date", "data", "created_by", "created_at", "updated_at"]);
export const GENERIC_TABLES = new Set([
  "plants", "licenses", "equipment_auth", "trainings", "training_matrix", "competency",
  "inspections", "incidents", "audits", "compliance", "loto", "permits", "escalation_matrix", "safety_reporting_cases",
]);

export const BULK_IMPORT_RESOURCES = new Set([
  "employees",
  "equipment-safety-assets",
  "contractors",
  "fire-devices",
  "trainings",
]);

export const COLUMNS: Record<string, Set<string>> = {
  users: new Set(["id", "name", "email", "role", "is_active", "avatar", "joined_at", "auth_user_id"]),
  posts: new Set(["id", "title", "content", "author_id", "section_id", "status", "created_at", "tags"]),
  sections: new Set(["id", "name", "slug", "description", "is_visible", "order"]),
  form_templates: new Set(["id", "title", "description", "fields", "created_at", "status"]),
  reports: new Set(["id", "title", "type", "generated_by", "created_at", "status", "data"]),
  activity_logs: new Set(["id", "action", "details", "performed_by", "performed_by_name", "timestamp", "module"]),
  employees: new Set(["id", "name", "email", "title", "department_id", "is_primary", "employee_id", "department", "factory", "section", "nationality", "joining_date", "supervisor", "phone", "medical_status", "ppe_issued", "incidents_count", "ncr_count", "trainings_completed", "status", "photo_url", "digital_signature", "qr_code_data", "user_id", "employee_type", "hse_area", "shift", "violations_count", "created_at", "updated_at"]),
  routing_rules: new Set(["id", "department_id", "severity", "recipient_ids"]),
  permissions: new Set(["id", "role", "module", "actions"]),
  documents: new Set(["id", "doc_type", "ref_no", "title", "date", "vendor", "department", "status", "category", "description", "amount", "expiry_date", "metadata", "pdf_url", "extracted_data", "created_by", "created_at", "updated_at"]),
  section_config: new Set(["id", "section_type", "categories", "required_fields", "number_prefix", "number_format"]),
  email_config: new Set(["id", "smtp_host", "smtp_port", "username", "password", "from_name", "from_email", "enable_sending", "signature"]),
  report_settings: new Set(["id", "plant_prefix", "date_format", "reset_rule", "company_name", "company_logo", "template_title", "public_base_url"]),
  site_settings: new Set(["id", "site_name", "description", "allow_registration", "maintenance_mode", "language", "theme", "color_theme", "branding"]),
  plants: GENERIC_COLUMNS,
  licenses: GENERIC_COLUMNS,
  equipment_auth: GENERIC_COLUMNS,
  trainings: GENERIC_COLUMNS,
  training_matrix: GENERIC_COLUMNS,
  competency: GENERIC_COLUMNS,
  inspections: GENERIC_COLUMNS,
  incidents: GENERIC_COLUMNS,
  audits: GENERIC_COLUMNS,
  audit_programs: new Set(["id","audit_no","title","audit_type","standard","department","factory","area","lead_auditor_user_id","planned_date","completed_date","status","scope","objective","summary","created_by","created_at","updated_at"]),
  audit_findings: new Set(["id","audit_id","finding_no","clause","finding_type","title","description","evidence","owner_user_id","due_date","status","action_id","verified_by","verified_at","created_by","created_at","updated_at"]),
  compliance: GENERIC_COLUMNS,
  legal_requirements: new Set(["id","requirement_no","authority","framework","clause","title","requirement","department","factory","owner_user_id","applicability","compliance_status","review_date","next_review_date","evidence_summary","gap_description","action_id","created_by","created_at","updated_at"]),
  compliance_evidence: new Set(["id","requirement_id","evidence_type","title","file_url","reference_no","valid_from","valid_until","notes","uploaded_by","uploaded_at"]),
  loto: GENERIC_COLUMNS,
  permits: GENERIC_COLUMNS,
  safety_reporting_cases: GENERIC_COLUMNS,
  safety_reporting_messages: new Set(["id", "case_id", "sender_type", "message", "created_by", "created_at"]),
  safety_reporting_channels: new Set(["id", "channel", "is_enabled", "public_label_ar", "public_label_en", "destination", "config", "updated_at"]),
  escalation_matrix: GENERIC_COLUMNS,
  fire_gateways: new Set(["id","gateway_code","name","protocol","host","port","manufacturer","model","firmware","building","area","status","signal_quality","connected_devices","last_heartbeat_at","last_error","notes","config","created_at","updated_at"]),
  fire_panels: new Set(["id","panel_code","name","manufacturer","model","serial_number","building","floor","area","protocol","gateway_id","host","status","last_signal_at","last_test_at","next_test_at","notes","data","floor_plan_id","map_x","map_y","created_at","updated_at"]),
  fire_devices: new Set(["id","device_code","device_type","panel_id","zone_id","gateway_id","loop_no","address_no","building","floor","area","exact_location","manufacturer","model","serial_number","protocol","status","power_status","battery_level","isolated","last_signal_at","last_test_at","next_test_at","notes","data","floor_plan_id","map_x","map_y","created_at","updated_at"]),
  fire_device_events: new Set(["id","device_id","panel_id","gateway_id","event_type","severity","status","message","occurred_at","acknowledged_at","acknowledged_by","cleared_at","source","raw_payload","created_at"]),
  emergency_exits: new Set(["id","exit_code","name","building","floor","area","assembly_point","route_description","door_type","gateway_id","status","door_status","lock_status","panic_bar_status","exit_sign_status","emergency_light_status","emergency_light_battery","obstruction_status","last_signal_at","last_inspection_at","next_inspection_at","qr_code","notes","data","floor_plan_id","map_x","map_y","created_at","updated_at"]),
  emergency_exit_events: new Set(["id","exit_id","gateway_id","event_type","severity","status","message","occurred_at","acknowledged_at","acknowledged_by","cleared_at","source","raw_payload","created_at"]),
  hse_actions: new Set(["id","action_no","title","description","source_type","source_id","category","department","factory","area","priority","status","progress","owner_user_id","assigned_employee_id","due_at","evidence_required","verification_required","verified_by","verified_at","verification_notes","effectiveness_status","effectiveness_notes","escalation_level","created_by","created_at","updated_at","closed_at","metadata"]),
  hse_workflows: new Set(["id","workflow_no","title","status","source_type","source_id","department","factory","area","owner_user_id","created_by","created_at","updated_at","closed_at","metadata"]),
  hse_workflow_links: new Set(["id","workflow_id","from_type","from_id","to_type","to_id","relation","created_by","created_at"]),
  hse_workflow_events: new Set(["id","workflow_id","event_type","resource_type","resource_id","message","data","created_by","created_at"]),
  hse_action_comments: new Set(["id","action_id","comment","created_by","created_at"]),
  hse_action_evidence: new Set(["id","action_id","file_url","file_name","note","uploaded_by","uploaded_at"]),
  hse_action_history: new Set(["id","action_id","event_type","old_values","new_values","changed_by","changed_at"]),
  hse_escalation_rules: new Set(["id","name","priority","overdue_hours","escalation_level","target_role","active","created_at"]),
  hse_action_escalations: new Set(["id","action_id","rule_id","escalation_level","target_role","reason","status","escalated_at","acknowledged_at","acknowledged_by","notes"]),
  ptw_permits: new Set(["id","permit_no","permit_type","title","description","department","factory","area","location","requester_employee_id","issuer_user_id","hse_reviewer_user_id","approver_user_id","status","risk_level","start_at","expires_at","reviewed_at","approved_at","activated_at","suspended_at","closed_at","suspension_reason","closure_notes","precautions","required_ppe","gas_test_required","gas_test_result","loto_required","signatures","created_by","created_at","updated_at"]),
  loto_isolations: new Set(["id","loto_no","permit_id","equipment_name","asset_ref","department","factory","area","isolation_type","status","authorized_employee_id","verified_by_user_id","zero_energy_verified","start_at","verified_at","released_at","closed_at","notes","created_by","created_at","updated_at"]),
  loto_points: new Set(["id","isolation_id","point_code","energy_type","location","normal_state","isolated_state","verification_method","status","created_at"]),
  loto_locks: new Set(["id","isolation_id","point_id","lock_number","tag_number","applied_by_employee_id","applied_at","removed_at","status","notes"]),
  inspection_templates: new Set(["id","name","category","description","checklist","active","created_by","created_at","updated_at"]),
  inspection_schedules: new Set(["id","template_id","assigned_employee_id","factory","area","department","frequency","day_of_week","day_of_month","next_run_date","active","created_by","created_at","updated_at"]),
  inspection_tasks: new Set(["id","schedule_id","template_id","inspector_employee_id","title","department","factory","area","due_date","status","result","checklist_result","findings","notes","started_at","completed_at","action_id","created_at","updated_at"]),
  safety_observations: new Set(["id","observation_no","observed_at","observer_employee_id","observation_type","category","department","factory","area","description","severity","status","immediate_action","photo_urls","action_id","created_by","created_at","updated_at","closed_at"]),
  equipment_assets: new Set(["id","asset_code","name","equipment_type","serial_number","manufacturer","model","department","factory","area","status","risk_rating","qr_code","certificate_number","certificate_expiry","last_inspection_date","next_inspection_date","last_maintenance_date","next_maintenance_date","operator_authorization_required","loto_required","notes","data","created_by","created_at","updated_at"]),
  equipment_service_records: new Set(["id","asset_id","service_type","performed_at","next_due","result","provider","technician","notes","attachment_url","created_by","created_at"]),
  equipment_defects: new Set(["id","defect_no","asset_id","description","severity","status","reported_at","reported_by_employee_id","action_id","resolved_at","resolution_notes","verified_by_user_id","verified_at","created_at","updated_at"]),
  equipment_operator_authorizations: new Set(["id","asset_id","employee_id","authorization_type","issue_date","expiry_date","status","certificate_ref","notes","created_by","created_at"]),
  contractors: new Set(["id","contractor_code","name","company_registration","scope_of_work","main_contact","email","phone","contract_start","contract_end","insurance_expiry","status","safety_score","notes","created_by","created_at","updated_at"]),
  contractor_workers: new Set(["id","contractor_id","worker_no","name","national_id","job_title","phone","induction_date","induction_expiry","medical_expiry","competency_expiry","status","access_allowed","block_reason","created_at","updated_at"]),
  contractor_documents: new Set(["id","contractor_id","worker_id","document_type","reference_no","issue_date","expiry_date","status","critical_for_access","file_url","notes","created_by","created_at","updated_at"]),
  contractor_scorecards: new Set(["id","contractor_id","month","year","inspections","violations","incidents","overdue_actions","training_compliance","score","rating","notes","created_at","updated_at"]),
  chemicals: new Set(["id","chemical_code","product_name","manufacturer","cas_numbers","hazard_classes","pictograms","storage_area","compatibility_group","quantity","unit","max_allowed_quantity","product_expiry_date","risk_rating","required_ppe","spill_response","first_aid","disposal_method","qr_code","status","notes","created_by","created_at","updated_at"]),
  chemical_sds: new Set(["id","chemical_id","revision_date","review_due_date","language","file_url","status","notes","uploaded_by","uploaded_at"]),
  chemical_inventory_transactions: new Set(["id","chemical_id","transaction_type","quantity","occurred_at","reference","notes","recorded_by"]),
  risk_register: new Set(["id","risk_no","title","hazard","activity","department","factory","area","owner_user_id","source_assessment_id","initial_likelihood","initial_severity","initial_score","initial_level","residual_likelihood","residual_severity","residual_score","residual_level","status","review_date","accepted_by","accepted_at","action_id","notes","created_by","created_at","updated_at"]),
  risk_controls: new Set(["id","risk_id","control_type","description","owner_employee_id","due_date","status","effectiveness","verified_at","verified_by","created_at","updated_at"]),
  site_floor_plans: new Set(["id","name","building","floor","image_url","width","height","active","created_by","created_at","updated_at"]),
  emergency_assembly_points: new Set(["id","point_code","name","building","area","capacity","map_x","map_y","status","created_at","updated_at"]),
  emergency_response_incidents: new Set(["id","response_no","source_type","source_id","title","severity","building","floor","area","status","alarm_started_at","evacuation_started_at","assembly_started_at","all_clear_at","primary_assembly_point_id","nearest_exit_ids","expected_count","accounted_count","missing_count","incident_id","action_id","created_at","updated_at"]),
  emergency_response_timeline: new Set(["id","response_id","event_type","message","occurred_at","recorded_by","data"]),
  emergency_muster_entries: new Set(["id","response_id","person_type","person_ref","person_name","department","assembly_point_id","status","accounted_at","notes"]),
  safety_map_points: new Set(["id","floor_plan_id","point_type","label","resource_type","resource_id","map_x","map_y","status","icon","details","created_by","created_at","updated_at"]),
  safety_qr_registry: new Set(["id","qr_code","resource_type","resource_id","label","route","status","metadata","created_at","updated_at"]),
  monthly_hse_reports: new Set(["id","report_no","month","year","status","snapshot","highlights","management_summary","next_month_plan","generated_by","generated_at","reviewed_by","reviewed_at","approved_by","approved_at","created_at","updated_at"]),
  hse_events: new Set(["id","event_type","source_type","source_id","severity","title","message","department","factory","area","occurred_at","data","created_by","created_at"]),
  notification_outbox: new Set(["id","event_id","channel","recipient","subject","body","payload","status","attempts","next_attempt_at","sent_at","last_error","created_by","created_at","updated_at"]),
  notification_rules: GENERIC_COLUMNS,
  integrations: GENERIC_COLUMNS,
  live_meetings: new Set(["id","room_code","title","provider","provider_room_name","status","created_by","started_at","ended_at","created_at","updated_at","access_mode","waiting_room"]),
  live_meeting_participants: new Set(["id","meeting_id","user_id","display_name","role","joined_at","left_at","created_at"]),
  live_meeting_messages: new Set(["id","meeting_id","user_id","sender_name","message","created_at"]),
};
