export type ResourceConfig = { table: string; module: string; single?: boolean; adminOnly?: boolean };

export const RESOURCE_MAP: Record<string, ResourceConfig> = {
  users: { table: "users", module: "users", adminOnly: true },
  posts: { table: "posts", module: "content" },
  sections: { table: "sections", module: "content" },
  forms: { table: "form_templates", module: "content" },
  reports: { table: "reports", module: "reports" },
  "activity-logs": { table: "activity_logs", module: "activity" },
  employees: { table: "employees", module: "employees" },
  "routing-rules": { table: "routing_rules", module: "settings" },
  permissions: { table: "permissions", module: "settings", adminOnly: true },
  documents: { table: "documents", module: "documents" },
  "section-config": { table: "section_config", module: "settings" },
  "email-settings": { table: "email_config", module: "settings", single: true, adminOnly: true },
  "report-settings": { table: "report_settings", module: "settings", single: true, adminOnly: true },
  "site-settings": { table: "site_settings", module: "settings", single: true, adminOnly: true },
  plants: { table: "plants", module: "settings" },
  licenses: { table: "licenses", module: "reports" },
  "equipment-auth": { table: "equipment_auth", module: "reports" },
  trainings: { table: "trainings", module: "reports" },
  "training-matrix": { table: "training_matrix", module: "reports" },
  competency: { table: "competency", module: "reports" },
  inspections: { table: "inspections", module: "reports" },
  incidents: { table: "incidents", module: "reports" },
  audits: { table: "audits", module: "reports" },
  compliance: { table: "compliance", module: "reports" },
  loto: { table: "loto", module: "reports" },
  permits: { table: "permits", module: "reports" },
  "safety-reporting": { table: "safety_reporting_cases", module: "reports" },
  "safety-reporting-messages": { table: "safety_reporting_messages", module: "reports" },
  "safety-reporting-channels": { table: "safety_reporting_channels", module: "settings" },
  "escalation-matrix": { table: "escalation_matrix", module: "reports" },
  "fire-gateways": { table: "fire_gateways", module: "reports" },
  "fire-panels": { table: "fire_panels", module: "reports" },
  "fire-devices": { table: "fire_devices", module: "reports" },
  "fire-device-events": { table: "fire_device_events", module: "reports" },
  "emergency-exits": { table: "emergency_exits", module: "reports" },
  "emergency-exit-events": { table: "emergency_exit_events", module: "reports" },
  "hse-actions": { table: "hse_actions", module: "reports" },
  "hse-action-comments": { table: "hse_action_comments", module: "reports" },
  "hse-action-evidence": { table: "hse_action_evidence", module: "reports" },
  "hse-action-history": { table: "hse_action_history", module: "reports" },
  "hse-escalation-rules": { table: "hse_escalation_rules", module: "reports" },
  "hse-action-escalations": { table: "hse_action_escalations", module: "reports" },
  "ptw-permits": { table: "ptw_permits", module: "reports" },
  "loto-isolations": { table: "loto_isolations", module: "reports" },
  "loto-points": { table: "loto_points", module: "reports" },
  "loto-locks": { table: "loto_locks", module: "reports" },
  "inspection-templates": { table: "inspection_templates", module: "reports" },
  "inspection-schedules": { table: "inspection_schedules", module: "reports" },
  "inspection-tasks": { table: "inspection_tasks", module: "reports" },
  "safety-observations": { table: "safety_observations", module: "reports" },
  "equipment-safety-assets": { table: "equipment_assets", module: "reports" },
  "equipment-service-records": { table: "equipment_service_records", module: "reports" },
  "equipment-defects": { table: "equipment_defects", module: "reports" },
  "equipment-operator-authorizations": { table: "equipment_operator_authorizations", module: "reports" },
  "contractors": { table: "contractors", module: "reports" },
  "contractor-workers": { table: "contractor_workers", module: "reports" },
  "contractor-documents": { table: "contractor_documents", module: "reports" },
  "contractor-scorecards": { table: "contractor_scorecards", module: "reports" },
  "chemicals": { table: "chemicals", module: "reports" },
  "chemical-sds": { table: "chemical_sds", module: "reports" },
  "chemical-transactions": { table: "chemical_inventory_transactions", module: "reports" },
  "risk-register": { table: "risk_register", module: "reports" },
  "risk-controls": { table: "risk_controls", module: "reports" },
  "site-floor-plans": { table: "site_floor_plans", module: "reports" },
  "emergency-assembly-points": { table: "emergency_assembly_points", module: "reports" },
  "emergency-responses": { table: "emergency_response_incidents", module: "reports" },
  "emergency-response-timeline": { table: "emergency_response_timeline", module: "reports" },
  "emergency-muster": { table: "emergency_muster_entries", module: "reports" },
  "safety-map-points": { table: "safety_map_points", module: "reports" },
  "safety-qr-registry": { table: "safety_qr_registry", module: "reports" },
  "monthly-hse-reports": { table: "monthly_hse_reports", module: "reports" },
  "hse-events": { table: "hse_events", module: "reports" },
  "notification-outbox": { table: "notification_outbox", module: "reports" },
  "notification-rules": { table: "notification_rules", module: "settings" },
  integrations: { table: "integrations", module: "settings" },
  "live-meetings": { table: "live_meetings", module: "content" },
  "live-meeting-participants": { table: "live_meeting_participants", module: "content" },
  "live-meeting-messages": { table: "live_meeting_messages", module: "content" },
};

