
create sequence if not exists public.hse_action_seq start 1;

create table if not exists public.hse_actions (
  id uuid primary key default gen_random_uuid(),
  action_no text not null unique default (
    'ACT-' || to_char(now(),'YYYY') || '-' || lpad(nextval('public.hse_action_seq')::text,6,'0')
  ),
  title text not null,
  description text,
  source_type text,
  source_id uuid,
  category text not null default 'General',
  department text,
  factory text,
  area text,
  priority text not null default 'Medium',
  status text not null default 'Open',
  progress integer not null default 0,
  owner_user_id uuid references public.users(id) on delete set null,
  assigned_employee_id uuid references public.employees(id) on delete set null,
  due_at timestamptz,
  evidence_required boolean not null default false,
  verification_required boolean not null default true,
  verified_by uuid references public.users(id) on delete set null,
  verified_at timestamptz,
  verification_notes text,
  effectiveness_status text not null default 'Not Reviewed',
  effectiveness_notes text,
  escalation_level integer not null default 0,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint hse_actions_priority_check check (priority in ('Critical','High','Medium','Low')),
  constraint hse_actions_status_check check (status in ('Open','In Progress','Blocked','Pending Verification','Completed','Closed','Cancelled')),
  constraint hse_actions_progress_check check (progress between 0 and 100),
  constraint hse_actions_effectiveness_check check (effectiveness_status in ('Not Reviewed','Effective','Partially Effective','Ineffective'))
);

create unique index if not exists uq_hse_actions_source_auto
  on public.hse_actions(source_type,source_id)
  where source_type is not null and source_id is not null and coalesce((metadata->>'autoGenerated')::boolean,false)=true;

create index if not exists idx_hse_actions_status_due on public.hse_actions(status,due_at);
create index if not exists idx_hse_actions_priority_status on public.hse_actions(priority,status);
create index if not exists idx_hse_actions_owner on public.hse_actions(owner_user_id,status);
create index if not exists idx_hse_actions_assignee on public.hse_actions(assigned_employee_id,status);
create index if not exists idx_hse_actions_source on public.hse_actions(source_type,source_id);

create table if not exists public.hse_action_comments (
  id uuid primary key default gen_random_uuid(),
  action_id uuid not null references public.hse_actions(id) on delete cascade,
  comment text not null,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_hse_action_comments_action on public.hse_action_comments(action_id,created_at);

create table if not exists public.hse_action_evidence (
  id uuid primary key default gen_random_uuid(),
  action_id uuid not null references public.hse_actions(id) on delete cascade,
  file_url text not null,
  file_name text,
  note text,
  uploaded_by uuid references public.users(id) on delete set null,
  uploaded_at timestamptz not null default now()
);

create index if not exists idx_hse_action_evidence_action on public.hse_action_evidence(action_id,uploaded_at);

create table if not exists public.hse_action_history (
  id uuid primary key default gen_random_uuid(),
  action_id uuid not null references public.hse_actions(id) on delete cascade,
  event_type text not null,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid references public.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists idx_hse_action_history_action on public.hse_action_history(action_id,changed_at desc);

create table if not exists public.hse_escalation_rules (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  priority text not null,
  overdue_hours integer not null default 0,
  escalation_level integer not null default 1,
  target_role text not null default 'manager',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint hse_escalation_rules_priority_check check (priority in ('Critical','High','Medium','Low')),
  constraint hse_escalation_rules_level_check check (escalation_level between 1 and 9),
  constraint hse_escalation_rules_hours_check check (overdue_hours >= 0)
);

create table if not exists public.hse_action_escalations (
  id uuid primary key default gen_random_uuid(),
  action_id uuid not null references public.hse_actions(id) on delete cascade,
  rule_id uuid references public.hse_escalation_rules(id) on delete set null,
  escalation_level integer not null,
  target_role text not null,
  reason text not null,
  status text not null default 'Open',
  escalated_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  acknowledged_by uuid references public.users(id) on delete set null,
  notes text,
  constraint hse_action_escalations_status_check check (status in ('Open','Acknowledged','Resolved')),
  unique(action_id,rule_id)
);

create index if not exists idx_hse_action_escalations_action on public.hse_action_escalations(action_id,escalated_at desc);
create index if not exists idx_hse_action_escalations_status on public.hse_action_escalations(status,escalated_at desc);

create or replace function private.current_app_user_id()
returns uuid
language sql
stable
security definer
set search_path=''
as $$
  select u.id
  from public.users u
  where u.auth_user_id=(select auth.uid())
  limit 1;
$$;

revoke all on function private.current_app_user_id() from public,anon,authenticated;

create or replace function public.touch_hse_action()
returns trigger
language plpgsql
security invoker
set search_path=pg_catalog,public
as $$
begin
  new.updated_at:=now();
  if new.status in ('Completed','Closed') and new.closed_at is null then
    new.closed_at:=now();
    if new.progress<100 then new.progress:=100; end if;
  elsif new.status not in ('Completed','Closed') then
    new.closed_at:=null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_touch_hse_action on public.hse_actions;
create trigger trg_touch_hse_action
before update on public.hse_actions
for each row execute function public.touch_hse_action();

create or replace function private.log_hse_action_history()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  actor uuid;
begin
  actor:=private.current_app_user_id();
  if tg_op='INSERT' then
    insert into public.hse_action_history(action_id,event_type,new_values,changed_by)
    values(new.id,'Created',to_jsonb(new),coalesce(actor,new.created_by));
    return new;
  elsif tg_op='UPDATE' then
    insert into public.hse_action_history(action_id,event_type,old_values,new_values,changed_by)
    values(new.id,'Updated',to_jsonb(old),to_jsonb(new),actor);
    return new;
  end if;
  return coalesce(new,old);
end;
$$;

revoke all on function private.log_hse_action_history() from public,anon,authenticated;

drop trigger if exists trg_log_hse_action_history on public.hse_actions;
create trigger trg_log_hse_action_history
after insert or update on public.hse_actions
for each row execute function private.log_hse_action_history();

create or replace function private.create_hse_action_if_absent(
  p_source_type text,
  p_source_id uuid,
  p_title text,
  p_description text,
  p_category text,
  p_priority text,
  p_department text,
  p_due_at timestamptz,
  p_created_by uuid default null,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare
  result_id uuid;
  normalized_priority text;
begin
  if p_source_type is null or p_source_id is null then return null; end if;
  normalized_priority:=case lower(coalesce(p_priority,'medium'))
    when 'critical' then 'Critical'
    when 'high' then 'High'
    when 'low' then 'Low'
    else 'Medium'
  end;

  select id into result_id
  from public.hse_actions
  where source_type=p_source_type
    and source_id=p_source_id
    and coalesce((metadata->>'autoGenerated')::boolean,false)=true
  limit 1;

  if result_id is not null then return result_id; end if;

  insert into public.hse_actions(
    title,description,source_type,source_id,category,department,priority,status,
    due_at,evidence_required,verification_required,created_by,metadata
  )
  values(
    coalesce(nullif(trim(p_title),''),p_source_type||' corrective action'),
    p_description,p_source_type,p_source_id,coalesce(p_category,'General'),p_department,
    normalized_priority,'Open',
    coalesce(p_due_at,now()+case normalized_priority
      when 'Critical' then interval '1 day'
      when 'High' then interval '3 days'
      when 'Medium' then interval '7 days'
      else interval '14 days'
    end),
    normalized_priority in ('Critical','High'),
    true,
    p_created_by,
    coalesce(p_metadata,'{}'::jsonb)||jsonb_build_object('autoGenerated',true)
  )
  returning id into result_id;

  return result_id;
exception
  when unique_violation then
    select id into result_id from public.hse_actions
    where source_type=p_source_type and source_id=p_source_id
      and coalesce((metadata->>'autoGenerated')::boolean,false)=true
    limit 1;
    return result_id;
end;
$$;

revoke all on function private.create_hse_action_if_absent(text,uuid,text,text,text,text,text,timestamptz,uuid,jsonb) from public,anon,authenticated;

create or replace function private.auto_action_from_ncr()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  due_ts timestamptz;
  creator uuid;
begin
  if lower(coalesce(new.status,'open')) in ('closed','cancelled') then return new; end if;
  creator:=case when nullif(new.created_by,'') is not null and new.created_by ~* '^[0-9a-f-]{36}$' then new.created_by::uuid else null end;
  if nullif(new.due_date,'') is not null and new.due_date ~ '^\d{4}-\d{2}-\d{2}$' then
    due_ts:=(new.due_date::date + time '17:00') at time zone 'Asia/Riyadh';
  end if;
  perform private.create_hse_action_if_absent(
    'NCR',new.id,
    'NCR '||coalesce(new.ref_no,'')||' - Corrective Action',
    coalesce(new.corrective_action,new.description),
    'NCR',
    coalesce(new.severity,'Medium'),
    new.department,
    due_ts,
    creator,
    jsonb_build_object('location',new.location,'refNo',new.ref_no)
  );
  return new;
end;
$$;
revoke all on function private.auto_action_from_ncr() from public,anon,authenticated;
drop trigger if exists trg_auto_action_ncr on public.ncr;
create trigger trg_auto_action_ncr after insert or update of corrective_action,status,due_date,severity on public.ncr
for each row execute function private.auto_action_from_ncr();

create or replace function private.auto_action_from_incident()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
declare
  sev text;
begin
  if lower(coalesce(new.status,'open')) in ('closed','cancelled') then return new; end if;
  sev:=coalesce(new.data->>'severity',new.data->>'riskLevel','High');
  perform private.create_hse_action_if_absent(
    'Incident',new.id,
    'Incident '||coalesce(new.ref_no,'')||' - Corrective Action',
    coalesce(new.data->>'description',new.title),
    'Incident',
    sev,
    new.department,
    null,
    new.created_by,
    jsonb_build_object('refNo',new.ref_no)
  );
  return new;
end;
$$;
revoke all on function private.auto_action_from_incident() from public,anon,authenticated;
drop trigger if exists trg_auto_action_incident on public.incidents;
create trigger trg_auto_action_incident after insert or update of status,data on public.incidents
for each row execute function private.auto_action_from_incident();

create or replace function private.auto_action_from_violation()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if lower(coalesce(new.status,'open')) in ('closed','cancelled') then return new; end if;
  if lower(coalesce(new.severity,'medium')) not in ('high','critical') then return new; end if;
  perform private.create_hse_action_if_absent(
    'Employee Violation',new.id,
    'Violation '||coalesce(new.ref_no,'')||' - Corrective Action',
    coalesce(new.violation,new.violation_description,new.notes),
    'Violation',
    new.severity,
    new.department,
    null,
    new.created_by,
    jsonb_build_object('employeeName',new.employee_name,'employeeId',new.employee_id,'factory',new.factory,'section',new.section)
  );
  return new;
end;
$$;
revoke all on function private.auto_action_from_violation() from public,anon,authenticated;
drop trigger if exists trg_auto_action_violation on public.employee_violations;
create trigger trg_auto_action_violation after insert or update of severity,status on public.employee_violations
for each row execute function private.auto_action_from_violation();

create or replace function private.auto_action_from_fire_event()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if lower(coalesce(new.severity,'info')) not in ('high','critical') then return new; end if;
  if new.event_type not in ('alarm','fault','offline') then return new; end if;
  perform private.create_hse_action_if_absent(
    'Fire Event',new.id,
    'Fire System '||replace(initcap(new.event_type),'_',' ')||' Action',
    new.message,
    'Fire Safety',
    new.severity,
    null,
    null,
    null,
    jsonb_build_object('deviceId',new.device_id,'panelId',new.panel_id,'gatewayId',new.gateway_id)
  );
  return new;
end;
$$;
revoke all on function private.auto_action_from_fire_event() from public,anon,authenticated;
drop trigger if exists trg_auto_action_fire_event on public.fire_device_events;
create trigger trg_auto_action_fire_event after insert on public.fire_device_events
for each row execute function private.auto_action_from_fire_event();

create or replace function private.auto_action_from_exit_event()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if lower(coalesce(new.severity,'info')) not in ('high','critical') then return new; end if;
  if new.event_type not in ('blocked','locked','offline','panic_bar_fault','exit_sign_fault','emergency_light_fault') then return new; end if;
  perform private.create_hse_action_if_absent(
    'Emergency Exit Event',new.id,
    'Emergency Exit '||replace(initcap(new.event_type),'_',' ')||' Action',
    new.message,
    'Emergency Preparedness',
    new.severity,
    null,
    null,
    null,
    null,
    jsonb_build_object('exitId',new.exit_id,'gatewayId',new.gateway_id)
  );
  return new;
end;
$$;
revoke all on function private.auto_action_from_exit_event() from public,anon,authenticated;
drop trigger if exists trg_auto_action_exit_event on public.emergency_exit_events;
create trigger trg_auto_action_exit_event after insert on public.emergency_exit_events
for each row execute function private.auto_action_from_exit_event();

insert into public.hse_escalation_rules(name,priority,overdue_hours,escalation_level,target_role,active)
select x.name,x.priority,x.overdue_hours,x.escalation_level,x.target_role,true
from (
  values
    ('Critical immediate escalation','Critical',0,1,'manager'),
    ('Critical executive escalation','Critical',24,2,'admin'),
    ('High overdue escalation','High',24,1,'manager'),
    ('High executive escalation','High',72,2,'admin'),
    ('Medium overdue escalation','Medium',72,1,'manager'),
    ('Low overdue escalation','Low',168,1,'manager')
) as x(name,priority,overdue_hours,escalation_level,target_role)
where not exists (
  select 1 from public.hse_escalation_rules r
  where r.name=x.name
);

create or replace function private.evaluate_hse_action_escalations()
returns integer
language plpgsql
security definer
set search_path=''
as $$
declare
  inserted_count integer:=0;
begin
  with eligible as (
    select
      a.id as action_id,
      r.id as rule_id,
      r.escalation_level,
      r.target_role,
      'Action '||a.action_no||' is overdue by escalation rule: '||r.name as reason
    from public.hse_actions a
    join public.hse_escalation_rules r
      on r.active=true and r.priority=a.priority
    where a.status not in ('Completed','Closed','Cancelled')
      and a.due_at is not null
      and now() >= a.due_at + make_interval(hours=>r.overdue_hours)
      and not exists (
        select 1 from public.hse_action_escalations e
        where e.action_id=a.id and e.rule_id=r.id
      )
  ), inserted as (
    insert into public.hse_action_escalations(action_id,rule_id,escalation_level,target_role,reason)
    select action_id,rule_id,escalation_level,target_role,reason from eligible
    returning action_id,escalation_level
  )
  select count(*) into inserted_count from inserted;

  update public.hse_actions a
  set escalation_level=x.max_level,updated_at=now()
  from (
    select action_id,max(escalation_level) max_level
    from public.hse_action_escalations
    where status in ('Open','Acknowledged')
    group by action_id
  ) x
  where a.id=x.action_id and a.escalation_level is distinct from x.max_level;

  return inserted_count;
end;
$$;

revoke all on function private.evaluate_hse_action_escalations() from public,anon,authenticated;

do $$
declare existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname='hse_action_escalation_hourly' limit 1;
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
  perform cron.schedule(
    'hse_action_escalation_hourly',
    '15 * * * *',
    'select private.evaluate_hse_action_escalations();'
  );
end $$;

alter table public.hse_actions enable row level security;
alter table public.hse_action_comments enable row level security;
alter table public.hse_action_evidence enable row level security;
alter table public.hse_action_history enable row level security;
alter table public.hse_escalation_rules enable row level security;
alter table public.hse_action_escalations enable row level security;

drop policy if exists hse_actions_select on public.hse_actions;
create policy hse_actions_select on public.hse_actions
for select to authenticated
using ((select private.has_app_role(array['admin','manager','editor','viewer']::text[])));

drop policy if exists hse_actions_write on public.hse_actions;
create policy hse_actions_write on public.hse_actions
for all to authenticated
using ((select private.has_app_role(array['admin','manager','editor']::text[])))
with check ((select private.has_app_role(array['admin','manager','editor']::text[])));

do $$
declare t text;
begin
  foreach t in array array['hse_action_comments','hse_action_evidence','hse_action_history','hse_escalation_rules','hse_action_escalations']
  loop
    execute format('drop policy if exists %I_select on public.%I',t,t);
    execute format(
      'create policy %I_select on public.%I for select to authenticated using ((select private.has_app_role(array[''admin'',''manager'',''editor'',''viewer'']::text[])))',
      t,t
    );
    execute format('drop policy if exists %I_write on public.%I',t,t);
    execute format(
      'create policy %I_write on public.%I for all to authenticated using ((select private.has_app_role(array[''admin'',''manager'',''editor'']::text[]))) with check ((select private.has_app_role(array[''admin'',''manager'',''editor'']::text[])))',
      t,t
    );
  end loop;
end $$;

grant select,insert,update,delete on public.hse_actions to authenticated;
grant select,insert,update,delete on public.hse_action_comments to authenticated;
grant select,insert,update,delete on public.hse_action_evidence to authenticated;
grant select,insert,update,delete on public.hse_action_history to authenticated;
grant select,insert,update,delete on public.hse_escalation_rules to authenticated;
grant select,insert,update,delete on public.hse_action_escalations to authenticated;

grant all on public.hse_actions to service_role;
grant all on public.hse_action_comments to service_role;
grant all on public.hse_action_evidence to service_role;
grant all on public.hse_action_history to service_role;
grant all on public.hse_escalation_rules to service_role;
grant all on public.hse_action_escalations to service_role;
