import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, DoorOpen, MapPin, RefreshCw, Siren, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useData } from "@/lib/data-context";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Dialog,DialogContent,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";

type Resp={id:string;responseNo:string;title:string;severity:string;building?:string|null;floor?:string|null;area?:string|null;status:string;alarmStartedAt:string;nearestExitIds:string[];expectedCount:number;accountedCount:number;missingCount:number;primaryAssemblyPointId?:string|null;};
type Exit={id:string;exitCode:string;name:string;status:string;area?:string|null;};
type AP={id:string;pointCode:string;name:string;status:string;};
type Muster={id:string;responseId:string;personType:string;personRef?:string|null;personName:string;department?:string|null;assemblyPointId?:string|null;status:string;accountedAt?:string|null;};
type Timeline={id:string;responseId:string;eventType:string;message?:string|null;occurredAt:string;};

const load=async<T,>(url:string):Promise<T>=>{const r=await apiRequest("GET",url);const p=await r.json();if(!r.ok)throw new Error(p?.error||"Unable to load");return p;};
const tone=(x:string)=>["Critical","Active","Missing"].includes(x)?"bg-red-500/10 text-red-700 border-red-500/30":["Accounted","All Clear","Closed"].includes(x)?"bg-emerald-500/10 text-emerald-700 border-emerald-500/30":"bg-amber-500/10 text-amber-700 border-amber-500/30";
export default function EmergencyResponsePage(){
 const {settings,currentUser}=useData();const isAr=settings.language==="ar";const qc=useQueryClient();
 const [selected,setSelected]=useState<Resp|null>(null);const [person,setPerson]=useState({personType:"Employee",personName:"",department:"",status:"Expected"});
 const responsesQ=useQuery<Resp[]>({queryKey:["emergency-responses"],queryFn:()=>load("/api/data?resource=emergency-responses")});
 const exitsQ=useQuery<Exit[]>({queryKey:["emergency-exits"],queryFn:()=>load("/api/data?resource=emergency-exits")});
 const apsQ=useQuery<AP[]>({queryKey:["assembly-points"],queryFn:()=>load("/api/data?resource=emergency-assembly-points")});
 const musterQ=useQuery<Muster[]>({queryKey:["muster",selected?.id],enabled:!!selected,queryFn:()=>load(`/api/data?resource=emergency-muster&responseId=${selected!.id}`)});
 const timelineQ=useQuery<Timeline[]>({queryKey:["timeline",selected?.id],enabled:!!selected,queryFn:()=>load(`/api/data?resource=emergency-response-timeline&responseId=${selected!.id}`)});
 const responses=responsesQ.data||[],exits=exitsQ.data||[],aps=apsQ.data||[],muster=musterQ.data||[],timeline=timelineQ.data||[];
 const patchResp=async(p:any)=>{if(!selected)return;const r=await apiRequest("PATCH",`/api/data?resource=emergency-responses&id=${selected.id}`,p);const b=await r.json();if(!r.ok)return toast.error(b?.error||"Update failed");setSelected(b);await qc.invalidateQueries({queryKey:["emergency-responses"]});};
 const addTimeline=async(type:string,msg:string)=>{if(!selected)return;await apiRequest("POST","/api/data?resource=emergency-response-timeline",{responseId:selected.id,eventType:type,message:msg,recordedBy:currentUser?.id||null,data:{}});await qc.invalidateQueries({queryKey:["timeline",selected.id]});};
 const addPerson=async()=>{if(!selected||!person.personName.trim())return;const r=await apiRequest("POST","/api/data?resource=emergency-muster",{responseId:selected.id,...person,assemblyPointId:selected.primaryAssemblyPointId||null});const b=await r.json();if(!r.ok)return toast.error(b?.error||"Unable to add muster person");setPerson({personType:"Employee",personName:"",department:"",status:"Expected"});await qc.invalidateQueries({queryKey:["muster",selected.id]});await qc.invalidateQueries({queryKey:["emergency-responses"]});};
 const mark=async(m:Muster,status:string)=>{const r=await apiRequest("PATCH",`/api/data?resource=emergency-muster&id=${m.id}`,{status,accountedAt:status==="Accounted"?new Date().toISOString():null});const b=await r.json();if(!r.ok)return toast.error(b?.error||"Update failed");await qc.invalidateQueries({queryKey:["muster",selected?.id]});await qc.invalidateQueries({queryKey:["emergency-responses"]});};
 return <div className="space-y-5" dir={isAr?"rtl":"ltr"}>
  <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-red-600 text-white"><Siren className="h-6 w-6"/></div><div><h1 className="text-2xl font-bold">{isAr?"الاستجابة للطوارئ وMuster":"Emergency Response & Muster"}</h1><p className="text-xs text-muted-foreground">{isAr?"يُنشأ تلقائيًا من إنذارات الحريق الحرجة":"Automatically created from critical fire alarms"}</p></div></div><Button variant="outline" onClick={()=>qc.invalidateQueries()}><RefreshCw className="me-2 h-4 w-4"/>{isAr?"تحديث":"Refresh"}</Button></div>
  <div className="grid gap-3 sm:grid-cols-4"><Metric label={isAr?"نشطة":"Active"} value={responses.filter(r=>!["Closed","Cancelled","All Clear"].includes(r.status)).length}/><Metric label={isAr?"المتوقع":"Expected"} value={responses.reduce((n,r)=>n+r.expectedCount,0)}/><Metric label={isAr?"تم حصرهم":"Accounted"} value={responses.reduce((n,r)=>n+r.accountedCount,0)}/><Metric label={isAr?"مفقود":"Missing"} value={responses.reduce((n,r)=>n+r.missingCount,0)}/></div>
  <Card><CardContent className="overflow-x-auto p-4"><Table><TableHeader><TableRow><TableHead>{isAr?"الحدث":"Response"}</TableHead><TableHead>{isAr?"الموقع":"Location"}</TableHead><TableHead>{isAr?"الوقت":"Alarm"}</TableHead><TableHead>{isAr?"المخارج":"Nearest Exits"}</TableHead><TableHead>Muster</TableHead><TableHead>{isAr?"الحالة":"Status"}</TableHead></TableRow></TableHeader><TableBody>{responses.map(r=><TableRow key={r.id} className="cursor-pointer" onClick={()=>setSelected(r)}><TableCell><p className="font-semibold">{r.responseNo}</p><p className="text-xs text-muted-foreground">{r.title}</p></TableCell><TableCell>{r.building||"—"} / {r.area||"—"}</TableCell><TableCell>{new Date(r.alarmStartedAt).toLocaleString()}</TableCell><TableCell>{(r.nearestExitIds||[]).map(id=>exits.find(e=>e.id===id)?.exitCode||id.slice(0,6)).join(", ")||"—"}</TableCell><TableCell>{r.accountedCount}/{r.expectedCount} · <span className="text-red-600">{r.missingCount}</span></TableCell><TableCell><Badge variant="outline" className={tone(r.status)}>{r.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
  <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto">{selected&&<><DialogHeader><DialogTitle>{selected.responseNo} — {selected.title}</DialogTitle></DialogHeader>
   <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{void patchResp({status:"Evacuating",evacuationStartedAt:new Date().toISOString()});void addTimeline("Evacuation Started","Evacuation initiated");}}>{isAr?"بدء الإخلاء":"Start Evacuation"}</Button><Button variant="outline" onClick={()=>{void patchResp({status:"Muster",assemblyStartedAt:new Date().toISOString()});void addTimeline("Muster Started","Muster/headcount started");}}>{isAr?"بدء التجمع":"Start Muster"}</Button><Button onClick={()=>{void patchResp({status:"All Clear",allClearAt:new Date().toISOString()});void addTimeline("All Clear","All clear declared");}}>{isAr?"All Clear":"All Clear"}</Button></div>
   <div className="grid gap-3 md:grid-cols-3"><Info label={isAr?"نقطة التجمع":"Assembly"} value={aps.find(a=>a.id===selected.primaryAssemblyPointId)?.name||"—"}/><Info label={isAr?"المتوقع":"Expected"} value={String(selected.expectedCount)}/><Info label={isAr?"مفقود":"Missing"} value={String(selected.missingCount)}/></div>
   <Card><CardContent className="space-y-3 p-4"><h3 className="font-semibold">{isAr?"الحصر":"Muster"}</h3><div className="grid gap-2 md:grid-cols-5"><Select value={person.personType} onValueChange={v=>setPerson({...person,personType:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Employee","Contractor","Visitor"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Input placeholder={isAr?"الاسم":"Name"} value={person.personName} onChange={e=>setPerson({...person,personName:e.target.value})}/><Input placeholder={isAr?"القسم":"Department"} value={person.department} onChange={e=>setPerson({...person,department:e.target.value})}/><Select value={person.status} onValueChange={v=>setPerson({...person,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Expected","Accounted","Missing","Exempt"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Button onClick={()=>void addPerson()}>{isAr?"إضافة":"Add"}</Button></div><div className="space-y-2">{muster.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><div><p className="font-medium">{m.personName}</p><p className="text-xs text-muted-foreground">{m.personType} · {m.department||"—"}</p></div><div className="flex gap-2"><Badge variant="outline" className={tone(m.status)}>{m.status}</Badge><Button size="sm" variant="outline" onClick={()=>void mark(m,"Accounted")}>{isAr?"حاضر":"Accounted"}</Button><Button size="sm" variant="destructive" onClick={()=>void mark(m,"Missing")}>{isAr?"مفقود":"Missing"}</Button></div></div>)}</div></CardContent></Card>
   <Card><CardContent className="space-y-2 p-4"><h3 className="font-semibold">{isAr?"الخط الزمني":"Timeline"}</h3>{timeline.map(t=><div key={t.id} className="flex gap-3 border-s py-1 ps-3"><div><p className="font-medium">{t.eventType}</p><p className="text-xs text-muted-foreground">{t.message||""} · {new Date(t.occurredAt).toLocaleString()}</p></div></div>)}</CardContent></Card>
  </>}</DialogContent></Dialog>
 </div>;
}
function Metric({label,value}:{label:string;value:number}){return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>}
