import { useEffect, useRef, useState } from "react";
import { useLocation } from "wouter";
import { Camera, ExternalLink, QrCode, Search, Smartphone, X, Wifi, WifiOff, ClipboardPlus, RefreshCw, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { useData } from "@/lib/data-context";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { enqueueFieldOperation, listFieldOperations, deleteFieldOperation } from "@/lib/offline-field-queue";

type QrRecord={id:string;qrCode:string;resourceType:string;resourceId:string;label:string;route:string;status:string;metadata:Record<string,any>;};

export default function MobileFieldPage(){
 const {settings}=useData();const isAr=settings.language==="ar";const [,setLocation]=useLocation();
 const [code,setCode]=useState("");const [record,setRecord]=useState<QrRecord|null>(null);const [loading,setLoading]=useState(false);const [scanning,setScanning]=useState(false);
 const [online,setOnline]=useState(()=>navigator.onLine);const [queued,setQueued]=useState(0);const [syncing,setSyncing]=useState(false);
 const [observation,setObservation]=useState("");const [severity,setSeverity]=useState("Medium");
 const videoRef=useRef<HTMLVideoElement|null>(null);const streamRef=useRef<MediaStream|null>(null);const rafRef=useRef<number|null>(null);
 const stopScan=()=>{if(rafRef.current)cancelAnimationFrame(rafRef.current);rafRef.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;setScanning(false);};
 useEffect(()=>()=>stopScan(),[]);
 const refreshQueue=async()=>{try{setQueued((await listFieldOperations()).length);}catch{}};
 const syncQueue=async()=>{if(!navigator.onLine)return;setSyncing(true);try{const items=await listFieldOperations();for(const item of items){try{await apiRequest("POST",`/api/${item.resource}`,item.payload);await deleteFieldOperation(item.id);}catch{break;}}await refreshQueue();}finally{setSyncing(false);}};
 useEffect(()=>{void refreshQueue();const on=()=>{setOnline(true);void syncQueue();};const off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off);};},[]);
 const submitObservation=async()=>{const description=observation.trim();if(!description)return;const payload={observationNo:`OBS-${Date.now().toString(36).toUpperCase()}`,observedAt:new Date().toISOString(),observationType:"Unsafe Condition",category:"Field Observation",description,severity,status:"Open"};try{if(navigator.onLine){await apiRequest("POST","/api/safety-observations",payload);toast.success(isAr?"تم حفظ الملاحظة":"Observation saved");}else{await enqueueFieldOperation("safety-observations",payload);toast.success(isAr?"تم حفظ الملاحظة دون اتصال":"Observation queued offline");await refreshQueue();}setObservation("");}catch{await enqueueFieldOperation("safety-observations",payload);await refreshQueue();toast.success(isAr?"تم حفظها في قائمة المزامنة":"Saved to sync queue");}};
 const lookup=async(raw=code)=>{const value=raw.trim();if(!value)return;setLoading(true);try{const r=await apiRequest("GET",`/api/data?resource=qr-lookup&code=${encodeURIComponent(value)}`);const p=await r.json();if(!r.ok)throw new Error(p?.error||"Lookup failed");if(!p){setRecord(null);toast.error(isAr?"QR غير مسجل":"QR code is not registered");return;}setRecord(p);}catch(e:any){toast.error(e?.message||"Lookup failed");}finally{setLoading(false);}};
 const startScan=async()=>{const Detector=(window as any).BarcodeDetector;if(!Detector){toast.error(isAr?"المتصفح لا يدعم ماسح QR المباشر. استخدم إدخال الكود أو كاميرا النظام.":"This browser does not support direct QR scanning. Enter the code manually or use the system camera.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});streamRef.current=stream;setScanning(true);setTimeout(()=>{if(videoRef.current){videoRef.current.srcObject=stream;void videoRef.current.play();}},0);const detector=new Detector({formats:["qr_code"]});const tick=async()=>{if(!videoRef.current||!streamRef.current)return;try{const results=await detector.detect(videoRef.current);if(results?.[0]?.rawValue){const v=String(results[0].rawValue);setCode(v);stopScan();void lookup(v);return;}}catch{}rafRef.current=requestAnimationFrame(tick);};rafRef.current=requestAnimationFrame(tick);}catch{toast.error(isAr?"تعذر تشغيل الكاميرا. تحقق من صلاحية الكاميرا.":"Unable to start camera. Check camera permission.");stopScan();}};
 return <div className="mx-auto max-w-2xl space-y-4 pb-24" dir={isAr?"rtl":"ltr"}>
   <div className="flex items-center justify-between rounded-2xl border bg-card px-4 py-3 text-xs"><div className="flex items-center gap-2">{online?<Wifi className="h-4 w-4 text-emerald-600"/>:<WifiOff className="h-4 w-4 text-amber-500"/>}<span>{online?(isAr?"متصل":"Online"):(isAr?"وضع دون اتصال":"Offline")}</span><Badge variant="outline">{queued} {isAr?"بانتظار المزامنة":"queued"}</Badge></div><Button size="sm" variant="ghost" disabled={!online||syncing||queued===0} onClick={()=>void syncQueue()}>{syncing?<Loader2 className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}</Button></div>
   <div className="rounded-3xl bg-gradient-to-br from-blue-600 to-cyan-600 p-6 text-white shadow-lg"><div className="flex items-center gap-3"><div className="rounded-2xl bg-white/15 p-3"><Smartphone className="h-7 w-7"/></div><div><h1 className="text-2xl font-bold">{isAr?"الوضع الميداني للجوال":"Mobile Field Mode"}</h1><p className="text-sm text-white/80">{isAr?"امسح QR للوصول إلى سجل السلامة مباشرة":"Scan a QR code to open the safety record directly"}</p></div></div></div>
   <Card><CardContent className="space-y-3 p-4"><div className="flex gap-2"><Input value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void lookup()} placeholder={isAr?"أدخل QR / Asset code...":"Enter QR / asset code..."}/><Button onClick={()=>void lookup()} disabled={loading}><Search className="h-4 w-4"/></Button></div><Button className="h-14 w-full text-base" variant={scanning?"destructive":"outline"} onClick={()=>scanning?stopScan():void startScan()}>{scanning?<><X className="me-2 h-5 w-5"/>{isAr?"إيقاف الكاميرا":"Stop Camera"}</>:<><Camera className="me-2 h-5 w-5"/>{isAr?"مسح QR بالكاميرا":"Scan QR with Camera"}</>}</Button>{scanning&&<div className="overflow-hidden rounded-2xl border bg-black"><video ref={videoRef} playsInline muted className="aspect-[3/4] w-full object-cover"/></div>}</CardContent></Card>
   <Card><CardContent className="space-y-3 p-4"><div className="flex items-center gap-2 font-semibold"><ClipboardPlus className="h-4 w-4 text-emerald-600"/>{isAr?"ملاحظة سلامة سريعة":"Quick Safety Observation"}</div><Textarea value={observation} onChange={e=>setObservation(e.target.value)} rows={4} placeholder={isAr?"اكتب الملاحظة أو الحالة غير الآمنة...":"Describe the observation or unsafe condition..."}/><div className="flex gap-2"><select className="h-10 flex-1 rounded-md border bg-background px-3 text-sm" value={severity} onChange={e=>setSeverity(e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><Button onClick={()=>void submitObservation()} disabled={!observation.trim()}>{isAr?"حفظ":"Save"}</Button></div><p className="text-[11px] text-muted-foreground">{isAr?"إذا انقطع الإنترنت سيتم حفظ الملاحظة محليًا ومزامنتها عند عودة الاتصال.":"If connectivity drops, the observation is stored locally and synced when the device reconnects."}</p></CardContent></Card>
   {record&&<Card className="overflow-hidden border-2 border-blue-500/20"><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-blue-500/10 p-2 text-blue-600"><QrCode className="h-5 w-5"/></div><div><p className="text-lg font-bold">{record.label}</p><p className="text-xs text-muted-foreground">{record.qrCode}</p></div></div><Badge>{record.resourceType}</Badge></div><div className="grid gap-2 sm:grid-cols-2">{Object.entries(record.metadata||{}).map(([k,v])=><div key={k} className="rounded-xl border p-3"><p className="text-[11px] uppercase text-muted-foreground">{k}</p><p className="mt-1 break-words text-sm font-medium">{String(v??"—")}</p></div>)}</div><Button className="h-12 w-full" onClick={()=>setLocation(record.route)}><ExternalLink className="me-2 h-4 w-4"/>{isAr?"فتح السجل الكامل":"Open Full Record"}</Button></CardContent></Card>}
   <div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-xs text-amber-800 dark:bg-amber-950/20 dark:text-amber-200">{isAr?"عند استخدام الكاميرا، المعالجة تتم داخل المتصفح ولا يتم رفع بث الفيديو إلى الخادم.":"When using the camera, QR detection runs in the browser; the video stream is not uploaded to the server."}</div>
 </div>;
}
