import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const COLORS = ["#991b1b", "#dc2626", "#f59e0b", "#eab308", "#f97316", "#2563eb", "#059669"];

type Level = { id:string; nameEn:string; nameAr:string; order:number };
type Count = { id:string; count:number };

function decode<T>(value:string | null, fallback:T):T {
  if (!value) return fallback;
  try { return JSON.parse(value) as T; } catch { return fallback; }
}

export default function SafetyPyramidPrintPage(){
  const [location] = useLocation();
  const [printed,setPrinted] = useState(false);
  const query = useMemo(()=>new URLSearchParams(location.split("?")[1] || ""),[location]);
  const isAr = query.get("lang") === "ar";
  const levels = decode<Level[]>(query.get("levels"),[]).sort((a,b)=>a.order-b.order);
  const counts = decode<Count[]>(query.get("counts"),[]);
  const incidents = Number(query.get("incidents") || 0);
  const nearMisses = Number(query.get("nearMisses") || 0);
  const observations = Number(query.get("observations") || 0);

  const getCount = (id:string) => counts.find(x=>x.id===id)?.count ?? 0;

  useEffect(()=>{
    if(printed || !levels.length) return;
    const timer = window.setTimeout(()=>{ setPrinted(true); window.print(); }, 250);
    return ()=>window.clearTimeout(timer);
  },[printed, levels.length]);

  const center=450, topWidth=120, bottomWidth=760, segmentHeight=84, topY=12;
  const step = levels.length > 1 ? (bottomWidth-topWidth)/(levels.length-1) : 0;
  const height = topY + levels.length*segmentHeight + 20;
  const title = isAr ? "الهرم الأمني الديناميكي" : "Dynamic Safety Pyramid";
  const subtitle = isAr ? "التقرير المرئي للهرم الأمني" : "Visual Safety Pyramid Report";
  const date = new Date().toLocaleDateString(isAr ? "ar-SA" : "en-US");

  return <div className="print-page" dir={isAr?"rtl":"ltr"}>
    <style>{`@page{size:A4 portrait;margin:8mm}html,body,#root{margin:0!important;padding:0!important;background:#fff!important;color:#111827!important;font-family:Arial,"Segoe UI",sans-serif}body{min-width:0}.print-page{display:block!important;width:100%!important;max-width:794px!important;margin:0 auto!important;background:#fff!important;color:#111827!important;padding:0}.header{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;border-bottom:4px solid #dc2626;padding-bottom:10px;margin-bottom:12px}.header h1{margin:0;font-size:24px;line-height:1.15;font-weight:800}.header p{margin:4px 0 0;font-size:12px;color:#64748b}.meta{font-size:10px;color:#475569;text-align:right;white-space:nowrap}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.kpi{border:1px solid #cbd5e1;border-radius:7px;padding:8px;text-align:center;background:#f8fafc}.kpi strong{display:block;font-size:21px;color:#111827}.kpi span{display:block;margin-top:2px;font-size:9px;color:#64748b}.graphic{width:100%;display:block}.graphic svg{display:block;width:100%;height:auto;margin:0 auto;overflow:visible}.footer{display:flex;justify-content:space-between;gap:12px;margin-top:8px;padding-top:6px;border-top:1px solid #cbd5e1;color:#64748b;font-size:8px}@media print{.print-page{display:block!important}.graphic svg{width:100%!important;height:auto!important}}`}</style>
    <div className="header"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="meta">HSE-PYRAMID-01<br/>{date}</div></div>
    <div className="kpis"><div className="kpi"><strong>{incidents}</strong><span>{isAr?"إجمالي الحوادث":"Total Incidents"}</span></div><div className="kpi"><strong>{nearMisses}</strong><span>{isAr?"الوقائع الوشيكة":"Near Misses"}</span></div><div className="kpi"><strong>{observations}</strong><span>{isAr?"الأفعال والظروف غير الآمنة":"Unsafe Acts & Conditions"}</span></div></div>
    <div className="graphic"><svg xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 900 ${height}`} aria-label={title}>
      {levels.map((lvl,index)=>{
        const wTop=topWidth+step*index;
        const wBottom=index===levels.length-1?bottomWidth:topWidth+step*(index+1);
        const y=topY+index*segmentHeight;
        const label=isAr?lvl.nameAr:lvl.nameEn;
        const count=getCount(lvl.id);
        return <g key={lvl.id}><polygon points={`${center-wTop/2},${y} ${center+wTop/2},${y} ${center+wBottom/2},${y+segmentHeight} ${center-wBottom/2},${y+segmentHeight}`} fill={COLORS[index%COLORS.length]} stroke="#fff" strokeWidth="4"/><text x={center} y={y+34} textAnchor="middle" fontFamily="Arial,Segoe UI,sans-serif" fontSize={label.length>28?13:16} fontWeight="700" fill="#fff">{label}</text><text x={center} y={y+67} textAnchor="middle" fontFamily="Arial,Segoe UI,sans-serif" fontSize="25" fontWeight="800" fill="#fff">{count}</text></g>
      })}
    </svg></div>
    <div className="footer"><span>{isAr?"تم إنشاء التقرير من ABDULKAREM SAFETY BOARD":"Generated by ABDULKAREM SAFETY BOARD"}</span><span>{title}</span></div>
  </div>
}
