"use client";

import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useData } from "@/lib/data-context";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { UserCheck, Search, Printer, Eye, Trash2, Loader2 } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { QRCodeSVG } from "qrcode.react";
import { toast } from "sonner";
import PrintShareDialog from "@/components/print-share-dialog";

interface VisitorApiRow { id:string; refNo?:string|null; title?:string|null; status?:string|null; department?:string|null; date?:string|null; data?:Record<string,any>|null; }
export interface VisitorRecord { id:string; visitorName:string; company:string; nationalId:string; hostPerson:string; inductionStatus:string; checkInTime:string; checkOutTime?:string; badgeNo:string; }

const toVisitor=(row:VisitorApiRow):VisitorRecord=>{const d=row.data||{};return{id:row.id,visitorName:String(row.title||d.visitorName||""),company:String(d.company||""),nationalId:String(d.nationalId||""),hostPerson:String(d.hostPerson||row.department||""),inductionStatus:String(d.inductionStatus||row.status||""),checkInTime:String(d.checkInTime||row.date||""),checkOutTime:d.checkOutTime?String(d.checkOutTime):undefined,badgeNo:String(row.refNo||d.badgeNo||"")};};

export default function AdminVisitorsPage(){
  const {settings,currentUser}=useData(); const isAr=settings.language==="ar"; const queryClient=useQueryClient();
  const canDelete=currentUser?.role==="admin"||currentUser?.role==="manager";
  const [searchTerm,setSearchTerm]=useState(""); const [selectedVisitor,setSelectedVisitor]=useState<VisitorRecord|null>(null); const [deletingId,setDeletingId]=useState<string|null>(null);
  const [isPrintOpen,setIsPrintOpen]=useState(false); const [printItem,setPrintItem]=useState<any>(null);
  const {data:rows=[],isLoading}=useQuery<VisitorApiRow[]>({queryKey:["/api/visitors"],queryFn:async()=>{const r=await apiRequest("GET","/api/visitors");const p=await r.json();return Array.isArray(p)?p:[];},staleTime:0});
  const visitors=useMemo(()=>rows.map(toVisitor),[rows]);
  const filtered=useMemo(()=>{const q=searchTerm.trim().toLowerCase();return q?visitors.filter(v=>[v.visitorName,v.company,v.hostPerson,v.badgeNo].some(x=>x.toLowerCase().includes(q))):visitors;},[visitors,searchTerm]);
  const refresh=async()=>{await queryClient.invalidateQueries({queryKey:["/api/visitors"]});await queryClient.refetchQueries({queryKey:["/api/visitors"],type:"active"});};
  const handleDelete=async(item:VisitorRecord)=>{if(!canDelete)return;if(!window.confirm(isAr?`حذف سجل ${item.visitorName||item.badgeNo} نهائياً؟`:`Permanently delete ${item.visitorName||item.badgeNo}?`))return;setDeletingId(item.id);try{await apiRequest("DELETE",`/api/visitors/${encodeURIComponent(item.id)}`);if(selectedVisitor?.id===item.id)setSelectedVisitor(null);await refresh();toast.success(isAr?"تم حذف سجل الزائر نهائياً":"Visitor record deleted permanently");}catch(error:any){toast.error(error?.message||(isAr?"تعذر الحذف":"Unable to delete"));}finally{setDeletingId(null);}};
  const handlePrintVisitorBadge=(item:VisitorRecord)=>{setPrintItem({id:item.id,type:"license" as const,refNo:item.badgeNo,title:`${isAr?"بطاقة تصريح زائر / مقاول":"Visitor & Contractor Safety Pass"} - ${item.visitorName}`,department:item.hostPerson,status:item.inductionStatus,date:item.checkInTime,createdAt:item.checkInTime,sections:[{label:isAr?"رقم الشارة":"Badge No",value:item.badgeNo},{label:isAr?"الاسم":"Visitor Name",value:item.visitorName},{label:isAr?"الشركة":"Company",value:item.company},{label:isAr?"الهوية":"National ID",value:item.nationalId},{label:isAr?"المستضيف":"Host",value:item.hostPerson},{label:isAr?"حالة تعريف السلامة":"Induction Status",value:item.inductionStatus},{label:isAr?"وقت الدخول":"Check-In",value:item.checkInTime}]});setIsPrintOpen(true);};
  const handlePrintAll=()=>{if(filtered.length===0){toast.info(isAr?"لا توجد سجلات محفوظة للطباعة":"No saved visitor records to print");return;}setPrintItem({id:"VISITOR-REGISTER",type:"report" as const,refNo:"HSE-VISITOR-LOG",title:isAr?"سجل الزوار والمقاولين والتعريف بالسلامة":"Visitor & Contractor Safety Induction Log",department:"HSE / Security",status:"Active",date:new Date().toISOString().split("T")[0],sections:[{label:isAr?"عدد السجلات":"Total Records",value:String(filtered.length)},{label:isAr?"السجل":"Register",value:filtered.map(v=>`[${v.badgeNo}] ${v.visitorName} - ${v.company} - ${v.checkInTime}`).join("\n")} ]});setIsPrintOpen(true);};
  return <div className="space-y-6" data-testid="admin-visitors-page">
    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center"><UserCheck className="h-5 w-5 text-white"/></div><div><h2 className="text-[28px] font-bold tracking-tight">{isAr?"سجل الزوار والمقاولين والسلامة":"Visitor & Contractor Safety Induction"}</h2><p className="text-[12px] text-muted-foreground">{isAr?"يعرض فقط سجلات الزوار والمقاولين المحفوظة فعلياً":"Only visitor and contractor records saved in the database are displayed"}</p></div></div><Button onClick={handlePrintAll} variant="outline" className="gap-2"><Printer className="h-4 w-4"/>{isAr?"طباعة السجل":"Print Register"}</Button></div>
    <Card className="p-4 space-y-4"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground rtl:right-3 rtl:left-auto"/><Input placeholder={isAr?"البحث بالزائر أو الشركة...":"Search visitors..."} value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} className="pl-9 rtl:pr-9 rtl:pl-3"/></div><div className="rounded-lg border overflow-hidden"><Table><TableHeader className="bg-muted/50"><TableRow><TableHead>{isAr?"شارة الزائر":"Badge"}</TableHead><TableHead>{isAr?"الزائر والشركة":"Visitor & Company"}</TableHead><TableHead>{isAr?"المستضيف":"Host"}</TableHead><TableHead>{isAr?"تعريف السلامة":"Induction"}</TableHead><TableHead>{isAr?"وقت الدخول":"Check In"}</TableHead><TableHead>QR</TableHead><TableHead className="text-right">{isAr?"الإجراءات":"Actions"}</TableHead></TableRow></TableHeader><TableBody>
      {isLoading?<TableRow><TableCell colSpan={7} className="h-28 text-center"><Loader2 className="h-5 w-5 animate-spin mx-auto"/></TableCell></TableRow>:filtered.length===0?<TableRow><TableCell colSpan={7} className="h-28 text-center text-muted-foreground">{isAr?"لا توجد سجلات زوار محفوظة":"No saved visitor records"}</TableCell></TableRow>:filtered.map(item=><TableRow key={item.id}><TableCell className="font-mono text-xs font-semibold">{item.badgeNo||"—"}</TableCell><TableCell><p className="font-semibold text-sm">{item.visitorName||"—"}</p><p className="text-xs text-muted-foreground">{item.company||"—"}</p></TableCell><TableCell className="text-xs">{item.hostPerson||"—"}</TableCell><TableCell><Badge variant="outline">{item.inductionStatus||"—"}</Badge></TableCell><TableCell className="text-xs">{item.checkInTime||"—"}</TableCell><TableCell>{item.badgeNo?<QRCodeSVG value={`VISITOR:${item.badgeNo}`} size={30}/>:"—"}</TableCell><TableCell className="text-right"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" onClick={()=>handlePrintVisitorBadge(item)}><Printer className="h-4 w-4"/></Button><Button size="sm" variant="outline" className="h-8 gap-1 text-xs" onClick={()=>setSelectedVisitor(item)}><Eye className="h-3.5 w-3.5"/>{isAr?"معاينة":"Preview"}</Button>{canDelete&&<Button size="icon" variant="ghost" className="text-destructive hover:bg-destructive/10" onClick={()=>void handleDelete(item)} disabled={deletingId===item.id}>{deletingId===item.id?<Loader2 className="h-4 w-4 animate-spin"/>:<Trash2 className="h-4 w-4"/>}</Button>}</div></TableCell></TableRow>)}
    </TableBody></Table></div></Card>
    {selectedVisitor&&<Dialog open onOpenChange={open=>!open&&setSelectedVisitor(null)}><DialogContent className="max-w-md text-center"><DialogHeader><DialogTitle>{isAr?"شارة الزائر وتصريح السلامة":"Visitor Safety Pass"}</DialogTitle></DialogHeader><div className="p-6 border rounded-xl space-y-4"><h3 className="font-bold text-lg">{selectedVisitor.visitorName}</h3><p className="text-sm text-muted-foreground">{selectedVisitor.company}</p>{selectedVisitor.badgeNo&&<div className="flex justify-center"><QRCodeSVG value={`VISITOR:${selectedVisitor.badgeNo}:${selectedVisitor.visitorName}`} size={120}/></div>}<p className="font-mono text-xs">{selectedVisitor.badgeNo}</p></div><DialogFooter><Button variant="outline" onClick={()=>setSelectedVisitor(null)}>{isAr?"إغلاق":"Close"}</Button><Button onClick={()=>handlePrintVisitorBadge(selectedVisitor)}><Printer className="h-4 w-4 me-2"/>{isAr?"طباعة":"Print"}</Button></DialogFooter></DialogContent></Dialog>}
    {printItem&&<PrintShareDialog open={isPrintOpen} onOpenChange={setIsPrintOpen} item={printItem}/>} 
  </div>;
}
